# Generated by Django 4.2.6 on 2023-10-07 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apis',
            new_name='Users',
        ),
    ]
